class CONFIG:
    LIGHT_TIME_TO_POWER_COST = 5
    HEAVY_TIME_TO_POWER_COST = 10

    RUBBLE_VALUE_CLEAR_FOR_RESOURCE: float = 10.0
    RUBBLE_VALUE_CLEAR_FOR_WATER_BASE: float = 10.0
    RUBBLE_CLEAR_FOR_LICHEN_MAX_DISTANCE: int = 6
    RUBBLE_CLEAR_FOR_LICHEN_MULTIPLIER_CLEARING: int = 3
